name: NPM Audit Fix Run

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Use --force flag for npm audit fix?"
        required: true
        type: boolean
      base_branch:
        description: "Specify a base branch"
        required: false
        default: "main"
      script:
        description: "Specify the build script to run"
        required: true
        type: string
        default: "yarn build"
      package_manager:
        description: "Package manager to use (npm or yarn)"
        required: true
        type: string
        default: "yarn"
      yarn_version:
        description: "Yarn version to use (only if package_manager is yarn)"
        required: false
        type: string
        default: "3.2.3"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      force: ${{ inputs.force || false }}
      base_branch: ${{ inputs.base_branch || 'main' }}
      script: ${{ inputs.script || 'yarn build' }}
      package_manager: ${{ inputs.package_manager || 'yarn' }}
      yarn_version: ${{ inputs.yarn_version || '3.2.3' }}

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write
