name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"
      mode:
        description: "Run mode: cherry-pick or verify"
        required: false
        default: "cherry-pick"
      script:
        description: "Specify the build script to run"
        required: true
        type: string
        default: "yarn build"
      package_manager:
        description: "Package manager to use (npm or yarn)"
        required: true
        type: string
        default: "yarn"
      yarn_version:
        description: "Yarn version to use (only if package_manager is yarn)"
        required: false
        type: string
        default: "3.2.3"

  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    if: github.event_name == 'workflow_dispatch' || contains(fromJson(toJson(github.event.pull_request.labels)).*.name, 'review-required')
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "RebeccaStevens"
      repo-name: "issue-closed-labeler-action"
      base_branch: ${{ inputs.base_branch }}
      mode: ${{ github.event_name == 'pull_request' && 'verify' || inputs.mode }}
      script: ${{ inputs.script || 'yarn build' }}
      package_manager: ${{ inputs.package_manager || 'yarn' }}
      yarn_version: ${{ inputs.yarn_version || '3.2.3' }}
